
# TokyoNight Alacritty Colors
# Default colors
[window]
opacity = 0.9
dynamic_title = true
dimensions = { columns = 120, lines = 30 }

[colors.primary]
background = '#000000'
foreground = '#f2f2f2'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#ed254a'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#656c7a'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ed254a'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#656c7a'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'


[font]
size = 11

[font.bold]
family = "Cascadia Code"
style = "Bold"

[font.bold_italic]
family = "Monospace"
style = "Bold Italic"

[font.italic]
family = "Monospace"
style = "Italic"

[font.normal]
family = "Cascadia Code"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 20
y = 20






[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750
unfocused_hollow = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "Insert", mods = "Shift", action = "PasteSelection" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
]

[terminal]


[terminal.shell]
program = "/bin/zsh"
args = ["-c", "neofetch && exec zsh"]


