#!/usr/bin/bash
swww query || swww init
DIR="/home/tof/Images"
SLEEPTIME=360
while :
do
PIC=$(find $DIR/*.jpg | shuf -n1)
swww img $PIC --transition-type random --transition-step 10 --transition-fps 100
sleep $SLEEPTIME
continue
done
