$mainMod = SUPER

bind = $mainMod, w, killactive,
bind = $mainMod, V, togglefloating,
bind = $mainMod, P, pseudo,
bind = $mainMod, J, togglesplit,
bind = $mainMod, S, fullscreen
bind = SUPER, z, exec, killall waybar || waybar -c /home/tof/.config/waybar/config -s /home/tof/.config/waybar/style.css
bind=SUPER,ESCAPE,exec,hyprlock

bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, k, exec, foot
bind = $mainMod, x, exec, kitty spf
bind = $mainMod, f, exec, firefox
bind = $mainMod, a, exec, audacious -Q
bind = $mainMod, E, exec, dolphin
bind = $mainMod, SPACE, exec, wofi
bind = $mainMod, Delete, exec, wlogout
bind = $mainMod, m, exec, grimblast --notify save screen /home/tof/Documents/Imgs/screen-shot/sc.jpg
bind = $mainMod, c, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy
#bind = SUPER, TAB, overview:toggle, all



# Déplacer le focus (standard : flèches + HJLK pour vim-like)
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Déplacer les fenêtres (ajoutez SHIFT pour éviter conflits)
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d





# Workspaces
bind = SUPER, code:10, workspace, 1
bind = SUPER, code:11, workspace, 2
bind = SUPER, code:12, workspace, 3
bind = SUPER, code:13, workspace, 4
bind = SUPER, code:14, workspace, 5
bind = SUPER, code:15, workspace, 6
bind = SUPER, code:16, workspace, 7
bind = SUPER, code:17, workspace, 8
bind = SUPER, code:18, workspace, 9
bind = SUPER, code:19, workspace, 10

# Send to Workspaces
bind = SUPER_SHIFT, code:10, movetoworkspace, 1
bind = SUPER_SHIFT, code:11, movetoworkspace, 2
bind = SUPER_SHIFT, code:12, movetoworkspace, 3
bind = SUPER_SHIFT, code:13, movetoworkspace, 4
bind = SUPER_SHIFT, code:14, movetoworkspace, 5
bind = SUPER_SHIFT, code:15, movetoworkspace, 6
bind = SUPER_SHIFT, code:16, movetoworkspace, 7
bind = SUPER_SHIFT, code:17, movetoworkspace, 8
bind = SUPER_SHIFT, code:18, movetoworkspace, 9
bind = SUPER_SHIFT, code:19, movetoworkspace, 10

bind=SUPER,mouse_down,workspace,e+1
bind=SUPER,mouse_up,workspace,e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = , XF86AudioRaiseVolume, exec, ~/.config/hypr/scripts/notify_volume.sh up
bind = , XF86AudioLowerVolume, exec, ~/.config/hypr/scripts/notify_volume.sh down
bind = , XF86AudioMute, exec, ~/.config/hypr/scripts/notify_volume.sh mute
