general {
    gaps_in = 8
    gaps_out = 10
    border_size = 3
    col.active_border = rgba(202020ff) rgba(202020ff) 0deg
    col.inactive_border = rgba(000000FF)                       
    layout = dwindle
}

misc {
    disable_hyprland_logo = yes
}

decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 0.9
    fullscreen_opacity = 1.0
    blur {
        enabled = true
        size = 5
        passes = 5
        new_optimizations = on
        ignore_opacity = false
        xray = false
    }
    shadow {
        enabled = true
        range = 18
        render_power = 2
        sharp = false
        color = rgba(4040a088)    
        offset = 0 6                 
    }
}
