################################
# Visuel
################################

windowrulev2 = opacity 0.96 0.87, class:^(?i)kitty$
windowrulev2 = opacity 0.96 0.87, class:^(?i)foot$
windowrulev2 = opacity 0.99 0.99, class:^(?i)firefox$
windowrulev2 = opacity 0.80 0.80, class:^(?i)audacious$
windowrulev2 = opacity 1 1, class:^(?i)org.kde.dolphin$
windowrulev2 = opacity 0.80 0.60, class:^(?i)net.lutris.lutris$
windowrulev2 = opacity 0.80 0.80, class:^(?i)org.qbittorrent.qbittorrent$

windowrulev2 = tile, class:^(?i)kitty$
windowrulev2 = noblur, class:^(?i)firefox$
windowrulev2 = noblur, class:^(?i)org.kde.dolphin$


