-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mainMod = "SUPER"
local mainModShift = "SUPER + SHIFT"

-- Fenêtres et layouts
hl.bind(mainMod .. " + W", hl.dsp.window.close())
hl.bind(mainMod .. " + V", hl.dsp.window.float())
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + S", hl.dsp.window.fullscreen())

-- Waybar Verrouillage Workspaces
hl.bind(
    mainMod .. " + Z",
    hl.dsp.exec_cmd("killall waybar || waybar -c /home/tof/.config/waybar/config -s /home/tof/.config/waybar/style.css")
)

hl.bind(mainMod .. " + ESCAPE", hl.dsp.exec_cmd("hyprlock"))


-- Workspaces alt tab
hl.bind("SUPER + TAB", function()
    hl.plugin.hyprexpo.expo("toggle")
end)

-- Lanceurs
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("foot"))
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("kitty spf"))
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("opera-gx"))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("audacious -Q"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("pcmanfm-qt"))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("wofi"))
hl.bind(mainMod .. " + DELETE", hl.dsp.exec_cmd("wlogout"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("cliphist list | wofi --dmenu | cliphist decode | wl-copy"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("flatpak run com.vixalien.sticky"))

-- Navigation entre fenêtres
hl.bind(mainMod .. " + LEFT", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + RIGHT", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + UP", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + DOWN", hl.dsp.focus({ direction = "down" }))

-- Déplacement de la fenêtre active
hl.bind(mainModShift .. " + LEFT", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainModShift .. " + RIGHT", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainModShift .. " + UP", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainModShift .. " + DOWN", hl.dsp.window.move({ direction = "down" }))

-- Aller vers les workspaces 1 à 10
hl.bind(mainMod .. " + code:10", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + code:11", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + code:12", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + code:13", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + code:14", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + code:15", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + code:16", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + code:17", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + code:18", hl.dsp.focus({ workspace = 9 }))


-- redimentionner deplacer les fenetres
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })


-- Move active window to a workspace with mainMod + SHIFT + [0-9]
local fr_keys = {
    "ampersand", -- &  → workspace 1
    "eacute",    -- é  → workspace 2
    "quotedbl",   -- "  → workspace 3
    "apostrophe", -- '  → workspace 4
    "parenleft",  -- (  → workspace 5
    "minus",      -- -  → workspace 6
    "egrave",     -- è  → workspace 7
    "underscore", -- _  → workspace 8
    "ccedilla",   -- ç  → workspace 9
    "agrave",     -- à  → workspace 10
}

-- Super + Shift + touche de la rangée numérique :
-- déplace la fenêtre active vers le workspace correspondant
for i = 1, 10 do
    hl.bind(
        mainMod .. " + SHIFT + " .. fr_keys[i],
        hl.dsp.window.move({ workspace = i }),
        { description = "Move active window to workspace " .. i }
    )
end



-- Contrôle du volume audio
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(
    "~/.config/hypr/scripts/notify_volume.sh up"
))

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(
    "~/.config/hypr/scripts/notify_volume.sh down"
))

hl.bind("XF86AudioMute", hl.dsp.exec_cmd(
    "~/.config/hypr/scripts/notify_volume.sh mute"
))



















-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "Switch to next workspace" })
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }), { description = "Switch to previous workspace" })



