-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua

---@module 'hl'

-- ===== INCLUSION DES FICHIERS SOURCES =====
require("hardware")
require("look")
require("animations")
require("layouts")
require("windowrules")
require("binds")
-- ===========================================

hl.config({
    debug = {
        disable_logs = false,
    },
})

hl.workspace_rule({
    workspace = 1,
})

-- Variables d'environnement
hl.env("KITTY_DISABLE_WAYLAND", 0)
hl.env("HYPRCURSOR_THEME", "Bibata-Original-Ice")
hl.env("HYPRCURSOR_SIZE", 44)
hl.env("XCURSOR_THEME", "Bibata-Original-Ice")
hl.env("XCURSOR_SIZE", 44)
hl.env("QT_CURSOR_THEME", "Bibata-Original-Ice")
hl.env("QT_CURSOR_SIZE", 44)
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_MENU_PREFIX", "arch-")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("dunst")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("hyprctl setcursor Bibata-Original-Ice 44")
    hl.exec_cmd("[workspace 2 silent] opera-gx")
    hl.exec_cmd("[workspace 3 silent] audacious -Q")
    hl.exec_cmd("[workspace 1 silent] kitty")
    hl.exec_cmd("[workspace 8 silent] qbittorrent")
    hl.exec_cmd("sleep 0.5 && hyprpm reload")
    hl.exec_cmd("kbuildsycoca6 --noincremental")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle --config /home/tof/.config/hypr/hypridle.conf")
    hl.exec_cmd("sleep 1 && hyprsunset")
end)

-- Exec (run every reload)
hl.on("config.reloaded", function()
    hl.exec_cmd("~/.config/hypr/scripts/bgaction")
end)
