general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/tof/.config/hypr/img.jpg
    blur_passes = 0
    color = rgba(0,0,0,1)  # Optionnel, noir si l'image ne charge pas
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outline_color = rgba(220,220,220,0.9)   # Gris clair
    inner_color = rgba(255,255,255,0.85)    # Blanc légèrement transparent
    position = 0, 0
    text_color = rgba(30,30,30,1.0)         # Texte sombre pour contraste
    placeholder_text = Entrez votre mot de passe
    font_family = sans
    font_size = 18
}
