-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    dwindle = {
        preserve_split = true,
        -- pseudotile supprimé : utilise le dispatcher ci-dessous
    },
})

hl.config({
    binds = {
        workspace_back_and_forth = true,
        pass_mouse_when_bound = false,
    },
})
