-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        gaps_in = 8,
        gaps_out = 10,
        border_size = 2,
        layout = "scrolling",
        col = {
            active_border = { colors = { "rgba(202020ff)", "rgba(202020ff)" }, angle = 0 },
            inactive_border = "rgba(000000FF)",
        },
    },
})

hl.config({
    misc = {
        disable_hyprland_logo = true,
        session_lock_xray = true,
    },
})

hl.config({
    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        fullscreen_opacity = 1.0,
        blur = {
            enabled = true,
            size = 5,
            passes = 3,
            new_optimizations = true,
            ignore_opacity = true,
            xray = false,
        },
        shadow = {
            enabled = true,
            range = 3,
            render_power = 2,
            sharp = false,
            color = "rgba(80808088)",
            offset = "0 0",
        },
    },
})
