-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--###############################
-- Visuel
--###############################

-- Opacité par défaut pour toutes les fenêtres :
-- hl.window_rule({
--     name = "opacity_default",
--     match = {
--         class = ".*",
--     },
--     opacity = "0.80 0.80",
-- })

-- Opacité spécifique par application

hl.window_rule({
    name = "opacity_kitty",
    match = {
        class = "^(?i)kitty$",
    },
    opacity = "0.90 0.70",
})

hl.window_rule({
    name = "opacity_foot",
    match = {
        class = "^(?i)foot$",
    },
    opacity = "0.90 0.70",
})

hl.window_rule({
    name = "opacity_firefox",
    match = {
        class = "^(?i)firefox$",
    },
    opacity = "0.99 0.69",
})

hl.window_rule({
    name = "opacity_audacious",
    match = {
        class = "^(?i)audacious$",
    },
    opacity = "0.80 0.70",
})

hl.window_rule({
    name = "opacity_dolphin",
    match = {
        class = "^(?i)org.kde.dolphin$",
    },
    opacity = "0.90 0.80",
})

hl.window_rule({
    name = "opacity_lutris",
    match = {
        class = "^(?i)net.lutris.Lutris$",
    },
    opacity = "0.80 0.60",
})

hl.window_rule({
    name = "opacity_qbittorrent",
    match = {
        class = "^(?i)org.qbittorrent.qBittorrent$",
    },
    opacity

})
