#!/bin/bash

# Fonction pour afficher un carré plein
print_square() {
    echo -n "█"
}

# Fonction pour afficher un carré vide
print_empty_square() {
    echo -n "░"
}

# Récupérer les pourcentages d'utilisation du processeur
cpu_usage=$(mpstat 1 1 | awk '/^Average:/ {print 100 - $NF}')

# Calculer le nombre de carrés à afficher
num_squares=$((cpu_usage / 14))  # 14 = 100 / 7 (7 carrés)

# Afficher les carrés
for ((i = 0; i < 7; i++)); do
    if ((i < num_squares)); then
        print_square
    else
        print_empty_square
    fi
done

echo
