#!/usr/bin/bash
#swww query || swww init
pgrep -x swww-daemon >/dev/null || swww-daemon &
sleep 1
DIR="$HOME/Images"
SLEEPTIME=360
while :
do
PIC=$(find "$DIR" -type f \( -name "*.jpg" -o -name "*.png" -o -name "*.jpeg" \) | shuf -n1)
# PIC=$(find $DIR/*.jpg | shuf -n1)
swww img $PIC --transition-type random --transition-step 10 --transition-fps 100
sleep $SLEEPTIME
continue
done
