[main]
font=DejaVu Sans Mono:size=12

[colors]
background=000000
foreground=ffffff

# Couleurs normales (palette 0-7)
regular0=222222 # noir/gris très foncé
regular1=868686 # rouge/gris (adouci)
regular2=7a7a7a # vert/gris
regular3=aaaaaa # jaune/gris
regular4=5e5e5e # bleu/gris
regular5=8b8b8b # magenta/gris
regular6=aaaaaa # cyan/gris
regular7=e0e0e0 # blanc/gris clair

# Couleurs vives (palette 8-15)
bright0=444444 # noir/gris foncé
bright1=9a9a9a # rouge/gris clair
bright2=b0b0b0 # vert/gris clair
bright3=cccccc # jaune/gris clair
bright4=767676 # bleu/gris clair
bright5=bbbbbb # magenta/gris clair
bright6=dddddd # cyan/gris très clair
bright7=ffffff # blanc pur
